### ISSUE TITLE
Dockerfile not able to entrypoint.sh same directory

### ISSUE THREAD

**Issue by rahulvinodsharma** [RafikFarhad/push-to-gcr-github-action#10]
Files Structure 

```
- Container
  - Dockerfile
  - Entrypoint.sh
```

```
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy
      uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      with:
        gcloud_service_key: ${{ secrets.GCP_GCR_SA_KEY }}
        registry: gcr.io
        dockerfile: ./Container/Dockerfile
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        image_name: gcr.io/cc-devsecops/gitleaks-gsutil
```

**Error** 

```
Step 6/8 : COPY Entrypoint.sh /sbin/entrypoint.sh
COPY failed: file not found in build context or excluded by .dockerignore: stat Entrypoint.sh: file does not exist
Image building failed. Exiting ...
```

**Comment by RafikFarhad** [comment]
You should use `context` input as you changed the build context for docker. 
You may try this:
```
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy
      uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      with:
        gcloud_service_key: ${{ secrets.GCP_GCR_SA_KEY }}
        registry: gcr.io
        context: './Container' # <------------ UPDATE THIS ------------ 
        dockerfile: ./Container/Dockerfile
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        image_name: gcr.io/cc-devsecops/gitleaks-gsutil
```

And one optional thing is that you don't need to specify `dockerfile` as long as your Dockerfile has the name `Dockerfile`. This `gh-action` will look for `Dockerfile` in the build context you have provided. 


Please reopen the issue if it is not solved. Thanks for using 👊🏼
