### ISSUE TITLE
Is it possible to just push an image with this action?

### ISSUE THREAD

**Issue by twoversionsofme** [RafikFarhad/push-to-gcr-github-action#17]
I'm attempting to build a Spring Boot Java app (myproject), and publish it to GCP using `push-to-gcr-github-action`.  See my below action YAML.
```
name: Java CI with Gradle
on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main,master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: ./gradlew bootBuildImage -x test --stacktrace
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          registry: gcr.io
          project_id: myproject
          image_name: myproject
```
I'm getting the below error. I've already built the OCI container image using the Spring Boot Gradle plugin which provides and OCI image builder `bootBuildImage`.  I was hoping I could use this action to simply push the image. If not, the name of this action is misleading.
```
Run RafikFarhad/push-to-gcr-github-action@v3.0.2
  with:
    gcloud_service_key: ***
    registry: gcr.io
    project_id: myproject
    image_name: myproject
    image_tag: latest
    context: .
  env:
    JAVA_HOME_11.0.12_x64: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME_11_0_12_X64: /opt/hostedtoolcache/jdk/11.0.12/x64
/usr/bin/docker run --name c9e03698cfd506cc57486cb8c2546d9f8ba308_4ba1c1 --label c9e036 --workdir /github/workspace --rm -e JAVA_HOME_11.0.12_x64 -e JAVA_HOME -e JAVA_HOME_11_0_12_X64 -e INPUT_GCLOUD_SERVICE_KEY -e INPUT_REGISTRY -e INPUT_PROJECT_ID -e INPUT_IMAGE_NAME -e INPUT_IMAGE_TAG -e INPUT_DOCKERFILE -e INPUT_CONTEXT -e INPUT_TARGET -e INPUT_BUILD_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/myproject/myproject":"/github/workspace" c9e036:98cfd506cc57486cb8c2546d9f8ba308
Authenticating docker to gcloud ...
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Logged in to google cloud ...
Building image ...
docker build   -t myproject:temporary  .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
Image building failed. Exiting ...
```
