### ISSUE TITLE
base64 encoding a key that is stored as json does not work

### ISSUE THREAD

**Issue by pkaramol** [RafikFarhad/push-to-gcr-github-action#25]
My SA key is stored as json

However the following example fails

```yaml
    - name: base64 encode the staging gcr sa
      id: base64-staging-gcr
      shell: bash
      run:
        echo "::set-output name=STAGING_GCR_SA_BASE64::$(echo '${{ secrets.STAGING_GCR_SA }}' | python -m base64 -e)"

    - name: build and push to staging gcr
      id: stg_img_build
      uses: RafikFarhad/push-to-gcr-github-action@v4
      with:
        gcloud_service_key: ${{ steps.base64-staging-gcr.outputs.STAGING_GCR_SA_BASE64 }}
        registry: gcr.io
        project_id: $STAGING_GCR_PROJECT
        image_name: ${{ github.event.inputs.image_name }}
        image_tag:  ${{ github.event.inputs.image_tag }}
```

as follows:

```
Error response from daemon: Get "https://gcr.io/v2/": unknown: Unable to parse json key.
```
