### ISSUE TITLE
target parameter does not work

### ISSUE THREAD

**Issue by alexwenzel** [RafikFarhad/push-to-gcr-github-action#28]
Hi,

I have the following workflow:

```
jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: RafikFarhad/push-to-gcr-github-action@v4.1
                with:
                    gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
                    registry: eu.gcr.io
                    project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
                    image_name: prm
                    image_tag: dev
                    target: dev
```

and the following Dockerfile:

```
...

FROM base as local
# do local build

FROM base as dev
# do dev stage build
```

Your workflow does seem to ignore the `target` param because it always builds the local stage because it's the first one.
I would expect your target param to work like `--target dev` docker param.

**Comment by RafikFarhad** [comment]
Hi @alexwenzel, thanks for using this action.
If you see the [entrypoint of this action](https://github.com/RafikFarhad/push-to-gcr-github-action/blob/241707854fb71f655ec4e2a98bb16505f218bcc2/entrypoint.sh#L49), you can see that we are using `--target` if there is any target parameter provided. 
In your case, it is the default behavior, the prior build stages should be also run. [See here](https://stackoverflow.com/a/51254088/6189461)

There might be a solution (did not test by myself) using BuildKit and that can be achieved by running `export DOCKER_BUILDKIT=1` in an extra step before the build action. (Not tested by me).

I am also open to creating a new parameter for this action called `build_prefix` which can be used to prefix anything (for this case `DOCKER_BUILDKIT=1`) to the docker build command. Let me know if that helps. 
Thanks.

**Comment by alexwenzel** [comment]
hey, thanks for your input. 

i have enabled buildkit with your workflow with this line of code, before your workflow:

`-   run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV`

the full workflow looks like this:

```
jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
            -   uses: RafikFarhad/push-to-gcr-github-action@v4.1
                with:
                    gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
                    registry: eu.gcr.io
                    project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
                    image_name: prm
                    image_tag: dev
                    target: dev
```
