### ISSUE TITLE
GCLOUD_SERVICE_KEY is a required field 

### ISSUE THREAD

**Issue by jacksongoode** [RafikFarhad/push-to-gcr-github-action#40]
Using the example:
```yml
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:      
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.gcloud_service_key }}
          registry: gcr.io
          project_id: ...
          image_name: ...
          image_tag: ...
```

I get that the service key is needed. Reverted to 4.1 and this doesn't happen.
