### ISSUE TITLE
Integrate docker with github cache

### ISSUE THREAD

**Issue by SiddharthaMishra** [RafikFarhad/push-to-gcr-github-action#43]
It seems like you can use the github cache to cache docker layers and I've seen many docker push related github actions making use of this. I don't know how difficult it is to integrate so I just wanted to float the idea

**Comment by RafikFarhad** [comment]
Would you happen to have any examples? I have an impression that GH cache is not that good for docker build and I want to know if it has any benefit over GCR caching.

**Comment by tntchn** [comment]
Maybe using the buildx action from docker is easier to work with Github Action cache and this action can still help you to push the image to registry

This is my example workflow file:
```yml
name: Build and Push to GAR
on: [push]
jobs:
  build-and-push-to-gar:
    runs-on: ubuntu-latest
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: image-name
    steps:
      - uses: actions/checkout@v4
        # ↓ I usually work in my private repo so I need to run actions/checkout before setup-buildx-action
      - uses: docker/setup-buildx-action@v3
      
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # with this line buildx will load the image to docker
          tags: ${{ env.IMAGE_NAME }}:temporary # last step will load image name with :temporary tag
          cache-from: type=gha
          cache-to: type=gha,mode=max # if you use multi-stage builds you'll need max mode to cache all layers
          
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/123123123/locations/global/workloadIdentityPools/the-workload-pool/providers/the-provider
          service_account: only-artifact-writer@<PROJECT_ID>.iam.gserviceaccount.com
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: asia-docker.pkg.dev
          project_id: the-project/the-repo
          push_only: true
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest
```
