### ISSUE TITLE
Question about context path

### ISSUE THREAD

**Issue by Kakcalu13** [RafikFarhad/push-to-gcr-github-action#45]
The snippet below:

```
      - name: Push to GCR GitHub Action
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCR_SERVICE }}
          project_id: feagi-poc
          image_name: test
          image_tag: latest
          dockerfile: ./tmp/playground/Dockerfile
          context: /
```

The dockerfile I have is in `/tmp/playground`

how come I couldn't use like this:

```
          dockerfile: .Dockerfile
          context: ./tmp/playground
```

or 

```
          dockerfile: ./tmp/playground/Dockerfile
          context: ./tmp/playground
```

None of them worked. I'm unable to access to see where is the default path it is in. How do I direct `context` to get the `/tmp/playground`?

**Comment by RafikFarhad** [comment]
This should work except the `.` in front of Dockerfile
```
dockerfile: Dockerfile
context: ./tmp/playground
```

Build process will set the context first and will look for the `Dockerfile`

**Comment by Kakcalu13** [comment]
Thanks @RafikFarhad!

Testing it now

**Comment by Kakcalu13** [comment]
Unfortunately, that did not work. Sounds like it couldn't run the dockerfile anywhere, it has to be inside the current directory. See here:

I added one job before push to gcr. 

![image](https://github.com/RafikFarhad/push-to-gcr-github-action/assets/65916520/0bb8968c-7b54-4e32-b31a-6ba2d61cd9ac)

Then the next job (which is the same one as above plus your change/suggestion:
![image](https://github.com/RafikFarhad/push-to-gcr-github-action/assets/65916520/e80ad0fe-5855-4179-bd6b-70ae25ad97a5)



See the snippet of yml:

```
      - name: debugging playground
        working-directory: /tmp/playground
        run: |
          pwd
          echo "ls playground"
          ls
      - name: Push to GCR GitHub Action
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCR_SERVICE }}
          project_id: feagi-poc
          image_name: feagi-dev/playground
          image_tag: ${{ github.run_number }}, latest
          dockerfile: Dockerfile
          context: ./tmp/playground
```

Honestly, I don't see anything wrong with your suggestion. If you have more ideas, I'd love to hear them since I've hit the block now :(
