### ISSUE TITLE
Using `push_only` option causes the job to fail

### ISSUE THREAD

**Issue by jwickham-patchfox** [RafikFarhad/push-to-gcr-github-action#46]
I'm configuring an action to push an image built by a previous step and consequently am using the `push_only` option. However, this seems to cause the build to fail. Can you provide some guidance or verify that this is broken please?

action.yaml:
```
steps:
  - id: google_auth
    uses: google-github-actions/auth@v1
  - id: build-app
    run: # do the build step, resulting in an image
  - id: google-upload
    name: Upload image to Google Registry
    uses: RafikFarhad/push-to-gcr-github-action@v5-beta
    with:
      registry: ${{ env.REGISTRY_URL }}
      project_id: ${{ env.PROJECT_ID }}
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ env.IMAGES_STRING }}
      push_only: true
```

output:
```
... (omitted for brevity)
Authentication successful to [.... registry]...
Skipping image build ...
Fully qualified image name: [.....]myimage:develop
Creating docker tag ...
Error response from daemon: No such image: [.....]myimage:temporary
Pushing image [.....]myimage:develop ...
The push refers to repository [.....]myimage
tag does not exist: [.....]myimage:develop
Pushing failed. Exiting ...
```

Reading the logs and the `entrypoint.sh` code, I believe what is happening is the `TEMP_IMAGE_NAME` is set to `IMAGE_NAME:temporary` (note the `temporary` tag), then later in the loop over image tags, and the code creates the fully qualified image name with the specified image tag (e.g. `develop` or `latest`, whatever is configured in `image_tag` in the yaml). After this, we get 

```
docker tag $TEMP_IMAGE_NAME $IMAGE_NAME
```

which clearly is attempting to take the temp image which would have been built had I built it and create a new tag from it. However, since the build step didn't happen, it's attempting to create a new image tag from a nonexistent image (the one with `:temporary`), thus the attempt to create the `:develop` tag fails (this is the `Error response from daemon: no such image: [.....]myimage:temporary` line above). Since that fails, when it tries to push the `:develop` image, that image doesn't exist, causing the `tag does not exist` error.

Ideally, if doing a push-only solution, the `TEMP_IMAGE_NAME` wouldn't be used since we're not building a temporary image. 

If I'm using this incorrectly, can you please provide more detailed instructions on how to build an image in a previous step and then upload it here?

Thanks much!
