### ISSUE TITLE
Build and Upload to Google Artifact Registry

### ISSUE THREAD

**Issue by johnny-yeng** [RafikFarhad/push-to-gcr-github-action#48]
I'm trying to use [Direct Workload Identity Federation](https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation) in my GitHub Actions to directly authenticate and upload to Artifact Registry (without the need of creating any service account).
My steps:
1. Create WIF Pool and Provider
2. Give necessary IAM credentials
```
    gcloud artifacts repositories add-iam-policy-binding "REPO_NAME" \
  --project="PROJECT_NAME" \
  --role="roles/artifactregistry.writer" \
  --member="principalSet://iam.googleapis.com/projects/PROJECT_ID/locations/global/workloadIdentityPools/POOL_NAME/attribute.repository/GITHUB_ORG_NAME/*" --location="LOCATION"
```
4. My GitHub workflow yml
```
# Build and push Docker image to GCR
- name: Authenticate to Google Cloud
  id: auth
  uses: google-github-actions/auth@v2
  with:
    workload_identity_provider: projects/PROJECT_ID/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_NAME

- uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
  with:
    registry: REGISTRY_URL
    project_id: PROJECT_ID
    image_name: IMAGE_NAME
    dockerfile: ./Dockerfile
```
In theory this should work, but I keep on getting `denied: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.uploadArtifacts" on resource "projects/PROJECT_NAME/locations/LOCATION/repositories/REPO_NAME" (or it may not exist)
Pushing failed. Exiting ...`

---
Can anyone guide me on how to debug this issue or show hints about what I might missed? Thanks.
