### ISSUE TITLE
--build-args support results in empty args

### ISSUE THREAD

**Issue by jsnb** [RafikFarhad/push-to-gcr-github-action#8]
I'm attempting to set a secret and a github actions variable to env variables in my image but using the new build args mapping results in empty variables. The `docker build` command looks like what I would expect but the resulting containers don't have the variables set properly.

Dockerfile:
```
FROM python:3.6

ARG BUILD_ARG
ARG GIT_SHA
ENV BUILD_ARG=$BUILD_ARG
ENV GIT_SHA=$GIT_SHA

...

```

workflow.yaml:
```
      - name: environment variables
        run: |
          echo 'DOCKER_NAME=my-image' >> $GITHUB_ENV
          echo 'GCP_PROJECT_ID=my-project' >> $GITHUB_ENV
          echo 'MY_ENV_VAR=${{ secrets.MY_SECRET }}' >> $GITHUB_ENV

      - name: Publish to Google Container Registry
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.1
        with:
          gcloud_service_key: ${{ env.GCLOUD_SERVICE_ACCOUNT_KEY_B64 }}
          registry: us.gcr.io
          project_id: ${{ env.GCP_PROJECT_ID }}
          image_name: ${{ env.DOCKER_NAME }}
          build_args: BUILD_ARG=${{ env.MY_ENV_VAR }},GIT_SHA=${{ github.sha }}
```

log:
```
docker build  --build-arg BUILD_ARG=*** --build-arg GIT_SHA=xxxxxxxxxxxxxxxxxx  -t my-image:temporary  .
```
